experiment_name: perf_static_8dataloader_workers
log_dir: ../experiments/hsim/performance
epochs: 10
device: cuda:0
seed: 1
distrib_backend: NCCL
compute_metrics_per_action: True

transforms:
  ConvertToTensor:
    rank: 1
    params: null
#  DiscretizeDepth:
#    rank: 2
#    params:
#      n_channels: 5
#      min_depth: 0
#      max_depth: 0.5
  PermuteChannels:
    rank: 3
    params: null
  Resize:
    rank: 4
    params:
      size: [180, 320]
      interpolation: BILINEAR
  Normalize:
    rank: 5
    params: null

train:
  dataset:
    type: EgoMotionDataset
    params:
      data_root: /home/rpartsey/data/habitat/vo_datasets/noisy
      environment_dataset: gibson
      split: train  # train_train
      invert_rotations: False
    augmentations: null
  loader:
    type: EgoDataLoader
    params:
      batch_size: 16
      num_workers: 8
      shuffle: True
      sampler: null
  metrics:
    - translation_mae
    - rotation_mae

val:
  dataset:
    type: EgoMotionDataset
    params:
      data_root: /home/rpartsey/data/habitat/vo_datasets/noisy
      environment_dataset: gibson
      split: val
      invert_rotations: False
    augmentations: null
  loader:
    type: EgoDataLoader
    params:
      batch_size: 16
      num_workers: 8
      shuffle: False
      sampler: null
  metrics:
    - translation_mae
    - rotation_mae

model:
  type: VONetV3
  save: True
  params:
    encoder:
      type: resnet18
      params:
        depth: 5
        weights: null
        in_channels: 8
        in_height: 180
        in_width: 320
        base_planes: 32
        ngroups: 16 # base_planes // 2
        num_compression_channels: 35 # 2100 - flat size
    fc:
      params:
        hidden_size: [512, 512]
        output_size: 4
        p_dropout: 0.2
    collision_embedding_size: 0
    action_embedding_size: 8

loss:
  type: PoseLossV2
  params:
    alpha: 1.
    beta: 1.

optim:
  type: Adam
  params:
    lr: 0.0001

stopper:
  params:
    patience: 50
