experiment_name: resnet18_bs16_ddepth5_maxd0.5_randomsampling_dropout0.15_poseloss1._1._180x320_embedd_act_hc2021_vo2_joint
log_dir: ../experiments
epochs: 50
device: cuda:1
seed: 1

transforms:
  DiscretizeDepth:
    rank: 1
    params:
      n_channels: 5
      min_depth: 0
      max_depth: 0.5
  PermuteChannels:
    rank: 2
    params: null
  Resize:
    rank: 3
    params:
      size: [180, 320]
      interpolation: BILINEAR
  Normalize:
    rank: 4
    params: null

train:
  dataset:
    type: EgoMotionDataset
    params:
      data_root: /datasets/extra_space2/rpartsey/3d-navigation/habitat/pointnav-egomotion/vo/trajectory-noisy
      environment_dataset: gibson
      split: train
      invert_rotations: True
    augmentations: null
  loader:
    type: EgoDataLoader
    params:
      batch_size: 16
      num_workers: 10
      shuffle: True
      sampler: null
  metrics:
    - translation_mae
    - rotation_mae

val:
  dataset:
    type: EgoMotionDataset
    params:
      data_root: /datasets/extra_space2/rpartsey/3d-navigation/habitat/pointnav-egomotion/vo/trajectory-noisy
      environment_dataset: gibson
      split: val
      invert_rotations: False
    augmentations: null
  loader:
    type: EgoDataLoader
    params:
      batch_size: 16
      num_workers: 8
      shuffle: False
      sampler: null
  metrics:
    - translation_mae
    - rotation_mae

model:
  type: VONetV2
  save: True
  params:
    encoder:
      type: resnet18
      params:
        depth: 5
        weights: null
        in_channels: 18
        in_height: 180
        in_width: 320
        base_planes: 32
        ngroups: 16 # base_planes // 2
        num_compression_channels: 35 # 2100 - flat size
    fc:
      params:
        hidden_size: [512, 512]
        output_size: 4
        p_dropout: 0.15
    collision_embedding_size: 0
    action_embedding_size: 0

loss:
  type: PoseLoss
  params:
    alpha: 1.
    beta: 1.

optim:
  type: Adam
  params:
    lr: 0.0001

stopper:
  params:
    patience: 15
