experiment_name: smoke
data_root: /datasets/extra_space2/rpartsey/3d-navigation/habitat/pointnav-egomotion/vo/trajectory-noisy
log_dir: ./experiments
epochs: 30
device: cuda:0
seed: 1

train:
  dataset:
    type: EgoMotionDataset
    params:
      environment_dataset: gibson
      split: train
      invert_rotations: False
    transforms:
      DiscretizeDepth:
        params:
          n_channels: 0
          min_depth: null # 0
          max_depth: null # 1
      ConvertToTensor:
        params: null
      PermuteChannels:
        params: null
      Resize:
        params:
          size: [360, 640]
          interpolation: BILINEAR
      Normalize:
        params: null
  loader:
    type: EgoDataLoader
    params:
      batch_size: 16
      num_workers: 4
      shuffle: True
      sampler: null

val:
  dataset:
    type: EgoMotionDataset
    params:
      environment_dataset: gibson
      split: val
      invert_rotations: False
      d_depth_channels: 0
    transforms:
      DiscretizeDepth:
        params:
          n_channels: 0
          min_depth: null # 0
          max_depth: null # 1
      ConvertToTensor:
        params: null
      PermuteChannels:
        params: null
      Resize:
        params:
          size: [360, 640]
          interpolation: BILINEAR
      Normalize:
        params: null
  loader:
    type: EgoDataLoader
    params:
      batch_size: 16
      num_workers: 4
      shuffle: False
      sampler: null

model:
  type: VONet
  save: True
  params:
    encoder:
      type: resnet18
      params:
        depth: 5
        weights: null
        in_channels: 8
        in_height: 360
        in_width: 640
    fc:
      params:
        hidden_size: [512, 512]
        output_size: 4
        p_dropout: 0

loss:
  type: PoseLoss
  params:
    alpha: 1.
    beta: 10.

optim:
  type: Adam
  params:
    lr: 0.0001

stopper:
  params:
    patience: 12